<?php

namespace Voiture\FrontOfficeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CommentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentsRepository extends EntityRepository
{
	public function countComments()
	{
		$query = $this -> getEntityManager()->createQuery('
			SELECT COUNT(c.id)
			FROM VoitureFrontOfficeBundle:Comments c');

		return $query -> getSingleScalarResult();
	}
}
