<?php

namespace Voiture\FrontOfficeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GaragesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GaragesRepository extends EntityRepository
{
	public function getOneGarage()
	{
		$query = $this -> getEntityManager()-> createQuery('
			SELECT g 
			FROM VoitureFrontOfficeBundle:Garages g')
		->setMaxResults(1);

		return $query -> getSingleResult();
	}

	public function countGarage()
	{
		$query = $this -> getEntityManager()->createQuery('
			SELECT COUNT(g.id)
			FROM VoitureFrontOfficeBundle:Garages g');

		return $query ->getSingleScalarResult();
	}
}
