<?php

namespace Voiture\FrontOfficeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RegionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegionsRepository extends EntityRepository
{
	public function countRegions()
	{
		$query = $this -> getEntityManager()->createQuery('
			SELECT COUNT(r.id)
			FROM VoitureFrontOfficeBundle:Regions r');

		return $query ->getSingleScalarResult();
	}
}
